name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Check Out Source Code
      uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
        
      
    - name: Build Application
#      run: msbuild IWA.NET.sln /p:Configuration=Debug /t:Clean,Build
      run: msbuild IWA.NET.sln /t:Clean,Build

#    - name: Docker Login
#      uses: docker/login-action@v2
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file InsecureWebApp/Dockerfile --tag fortifydocker/iwa-dotnet:latest
    
#    - name: Push Docker image
#      run: docker push --all-tags fortifydocker/iwa-java
