name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Check Out Source Code
      uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file InsecureWebApp/Dockerfile --tag dylanbthomas/iwa-dotnet:latest
    
    - name: Push Docker image
      run: docker push --all-tags dylanbthomas/iwa-dotnet
